version: '3.7'
services:
  postgres-container:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5555'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data