version: '3.7'
services:
  postgres-container:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5555:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./create-postgresql-database.sh:/docker-entrypoint-initdb.d/create-postgresql-database.sh